# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-042acb8a-8488-46ff-8e4c-616524fd2820";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-042acb8a-8488-46ff-8e4c-616524fd2820".device = "/dev/disk/by-uuid/042acb8a-8488-46ff-8e4c-616524fd2820";

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-042acb8a-8488-46ff-8e4c-616524fd2820";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-042acb8a-8488-46ff-8e4c-616524fd2820";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FD08-3CC4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c7b7c463-bf1a-4b09-a351-e56b6c0bc0e7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
