# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-eacb0dcb-58e3-4900-99c0-0659aad00349";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-eacb0dcb-58e3-4900-99c0-0659aad00349".device = "/dev/disk/by-uuid/eacb0dcb-58e3-4900-99c0-0659aad00349";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-eacb0dcb-58e3-4900-99c0-0659aad00349";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-eacb0dcb-58e3-4900-99c0-0659aad00349";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/58DB-DCBA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # swapDevices commented out — LUKS-encrypted swap causes 90s boot timeout on VM
  # swapDevices =
  #   [ { device = "/dev/mapper/luks-c4e518d5-1a41-4c16-98b8-676fb78dff7e"; }
  #   ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
