# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6869ecbe-f9b5-43e8-8969-40aaf79bacae";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-6869ecbe-f9b5-43e8-8969-40aaf79bacae".device = "/dev/disk/by-uuid/6869ecbe-f9b5-43e8-8969-40aaf79bacae";
  boot.initrd.luks.devices."luks-93f2d63d-66a8-4d9d-8fed-33f20856bca3".device = "/dev/disk/by-uuid/93f2d63d-66a8-4d9d-8fed-33f20856bca3";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-6869ecbe-f9b5-43e8-8969-40aaf79bacae";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-6869ecbe-f9b5-43e8-8969-40aaf79bacae";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6D35-447F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-93f2d63d-66a8-4d9d-8fed-33f20856bca3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
